### ISSUE TITLE
Maintain YAMS

### ISSUE THREAD

**Issue by Deesen** [Deesen/YAMS#12]
I have only 4 months experience with Git so I´m not sure I am fit enough to take over. But I want to have an uptodate-YAMS ;-) so I would like to maintain it.

**Comment by goldsky** [comment]
https://help.github.com/articles/transferring-a-repository/#transferring-between-user-accounts
Remove your YAMS fork first.

**Comment by Deesen** [comment]
Ok removed it now.

**Comment by Deesen** [comment]
And thanks for all the good work you put into YAMS !

**Comment by goldsky** [comment]
And thanks to you for keeping this alive!
