### ISSUE TITLE
Warning: mysql_num_rows() expects parameter 1 to be resource

### ISSUE THREAD

**Issue by fourroses666** [Deesen/YAMS#13]
Hi Dennis,

Do you know if this is a YAMS bug?
https://forums.modx.com/thread/100311/problem-with-yams

**Comment by IanPercival** [comment]
I had the same issue. The fix for me was switching the 2 places I found calling mysql_* built in functions but a mysqli object was being returned.

*********
File:
class/yams.class.inc.php:2891

Change this:
return mysql_num_rows( $info );

To this
return mysqli_num_rows( $info );
*********


*********
File:
yams.module.inc.php:2565

Change this:
$row = mysql_fetch_assoc( $info );

To this
$row = mysqli_fetch_assoc( $info );
*********

This fixed all the errors

**Comment by modxuser** [comment]
@demaestro

As mentioned on the forum, are you actually using the latest version ? [Found Here](https://github.com/Deesen/YAMS)

**Comment by IanPercival** [comment]
Kind of a loaded question.... I have the latest Modx Evo. I searched YAMS in the package manager in the admin section and clicked install. So yes I have the latest version using that install path.

Using the above method YAMS 1.2-RC3 was installed, but I see as of this post it is at YAMS 1.2-RC5... so no I am not using the latest version, but neither is the ModX package manager.

**Comment by Deesen** [comment]
I asked dmi3yy via PM if we should replace extras/YAMS with my fork because this is the original fork.

**Comment by Deesen** [comment]
https://github.com/extras-evolution/YAMS is now based on https://github.com/Deesen/YAMS so package-manager should be up to date.

@fourroses666 Still issues or can be closed?

**Comment by fourroses666** [comment]
I don't know. I have no issues but neoziox did. Going to close this.

**Comment by modxuser** [comment]
"Loaded question" somewhat harsh if you ask me.

If you keep up with Evo development, you will know that a lot of the Q&A work is now directly via GitHub and less via the forum, so any tech questions, issues / bugs etc. should in my opinion go through GitHub and no-longer through the MODX LLC Forum

**Comment by fourroses666** [comment]
I'm not sure we want to have all questions on Github.
There are plans for a new forum on a different site but not sure if its going to be used.

**Comment by IanPercival** [comment]
Hey sorry if my comment was perceived poorly. I was having a case of the Mondays ;)

The plugin works great, Using the R5 version resolved all issues, Thanks you guys :)

**Comment by Deesen** [comment]
When they say, open-source is free of charge, they lie.. sometimes one can feel quite "charged" :-D
