### ISSUE TITLE
Tab lang content width 100%

### ISSUE THREAD

**Issue by fourroses666** [Deesen/YAMS#17]
Hi Dennis, 

Do you know where to change this table style? 
Looked true all YAMS files but can't find it.
I'd like to have it 100% width.

![width-100](https://cloud.githubusercontent.com/assets/523389/21498265/4e3d9928-cc2b-11e6-8231-53b73e222fc1.jpg)

![width](https://cloud.githubusercontent.com/assets/523389/21498266/4f2719f4-cc2b-11e6-8d26-8b7014eed495.jpg)

**Comment by Deesen** [comment]
I checked one live-installation with latest YAMS and MODX 1.2.1-beta and I have 100% width inputs by `<input style="width:100%" />`.. I am wondering its not the same for you? Can I have access?

**Comment by fourroses666** [comment]
The inputs are correct. Its the table which doesn't have 100% width.
Its auto width and there needs to be added width="100%".
Really tried to find the area / file where this is being placed.
Also checked managermanager but I have no idea.

I have added an user so you can see.

Or does it have to do with https://github.com/modxcms/evolution/issues/1144#issuecomment-269297524

Another option would be CSS but it needs a better class or id.

**Comment by Deesen** [comment]
Thanks I could find the difference, should be fixed now.

**Comment by fourroses666** [comment]
Thanks allot, thats a nice fix.
