### ISSUE TITLE
modx 1.2.0 update to 1.2.1 YAMS not working on frontend

### ISSUE THREAD

**Issue by eire69k** [Deesen/YAMS#18]
Hi there. I just finished an update to Modx 1.2.1 and my frontend shows me this message: "The nest of values are hard to read. Please use three different quotes."
And under "Modul/YAMS/ I can't even change any settings. I geht this messages.
Could not set redirection.
Could not set the http status for redirection to the default language.
Could not set the http status for redirection to non-default languages.
Could not set the http status for changing languages.
Could not set the list of index.php?id= document ids.
Could not set the URL conversion mode.
or
Failed to set active templates: Array( [22] =&gt; [10], ...
When I disable the YAMS Plugin, the webpage is showing up normal but without the funktion of course.

**Comment by Deesen** [comment]
The quotes issue is not related to YAMS but to nested snippet-calls and a new parser-mechanismn: https://github.com/modxcms/evolution/issues/1089#issuecomment-266869207

Reg "Could not set redirection" etc. maybe you config-file is not writeable? Maybe you need to change file-permissions for assets/modules/yams/yams.config.inc.php ?

**Comment by eire69k** [comment]
I have to apologize here. You were absolute right with both, Deesen.  1. The file-permissions I had before on that file was changed (strange...). And 2. it was my own custom snippet what has caused this issue. I will look to that new parser-mechanismn and fix that. I thank you a lot for that fast feedback on this!!

**Comment by Deesen** [comment]
Great! Then you can leave this issue open so I remember adding a check + warning-message in case the config-file is not writeable.
