### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by fabryshock** [Deesen/YAMS#21]
Hi,
i have a problem with Modx Evo 1.2 and YAMS RC5.
In event Log i have many log like this:
Plugin - YAMS / PHP Parse Error
Trying to get property of non-object
« MODX Parse Error »
Error : Undefined offset: 2
ErrorType[num] 	NOTICE[8]
File 	assets/modules/yams/class/yams.class.inc.php
Line 	2488
Source 	$urlRootName = $matches[2];
Current Plugin 	YAMS(OnWebPageInit)

**Comment by Deesen** [comment]
First of all its only a "notice" so no critical error. Nevertheless can you tell if it happens only on root like domain.com/en/ , or does it also happen on subpages? And if you have multiple errors in event-log, does it always happen in line 2488 or also in other lines?
