### ISSUE TITLE
mm_rules -> mm_renameField don't work

### ISSUE THREAD

**Issue by fourroses666** [Deesen/YAMS#5]
mm_renameField('pagetitle','Custom name here');
require( $modx->config['base_path'] . 'assets/modules/yams/yams.mm_rules.inc.php' );

when adding the require rule renaming fields doesn't work anymore.

**Comment by Deesen** [comment]
Is this issue still not solved?

**Comment by fourroses666** [comment]
Not solved, it works when using;
`mm_renameField('pagetitle_en','Custom name here');`

But not on pagetitle.
`mm_renameField('pagetitle','Custom name here');`

No big deal
