### ISSUE TITLE
just a little fix to make YAMS Tabs work with mm 0.6.2 

### ISSUE THREAD

**Issue by fourroses666** [Deesen/YAMS#7]
https://github.com/esszett/YAMS/commit/863e43871c700ceb38879019851fb8671666e725

https://github.com/modxcms/evolution/issues/313#issuecomment-55310424

**Comment by goldsky** [comment]
Anyone interested to take over this project?

**Comment by fourroses666** [comment]
Oké I will, a Fork does the job? 

*I have missed this reply somehow.
