### ISSUE TITLE
Multilingual alias not generating

### ISSUE THREAD

**Issue by pbowyer** [Deesen/YAMS#8]
[ Although this extension is not maintained, I live in hope someone will take it on ]

With MODX Evo 1.0.15 and the latest YAMS (1.2.0rc3) I cannot get the multilingual aliases to be automatically generated. I've checked the steps in http://forums.modx.com/thread/45544/fixed-autogenerating-multilingual-aliases---is-it-possible and everything is enabled.

**Comment by Deesen** [comment]
I cannot recreate it with latest RC4 / RC5. Is this issue still open after 1,5 years? If so please re-open it so we can solve it.
